/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/dashboard/components/modals/GameOneHpRemainingModal': RouteRecordInfo<'/dashboard/components/modals/GameOneHpRemainingModal', '/dashboard/components/modals/GameOneHpRemainingModal', Record<never, never>, Record<never, never>>,
    '/dashboard/components/modals/GameOverModal': RouteRecordInfo<'/dashboard/components/modals/GameOverModal', '/dashboard/components/modals/GameOverModal', Record<never, never>, Record<never, never>>,
    '/dashboard/components/shop/ShopList': RouteRecordInfo<'/dashboard/components/shop/ShopList', '/dashboard/components/shop/ShopList', Record<never, never>, Record<never, never>>,
    '/dashboard/components/shop/ShopListItem': RouteRecordInfo<'/dashboard/components/shop/ShopListItem', '/dashboard/components/shop/ShopListItem', Record<never, never>, Record<never, never>>,
    '/dashboard/components/tasks/TasksTable': RouteRecordInfo<'/dashboard/components/tasks/TasksTable', '/dashboard/components/tasks/TasksTable', Record<never, never>, Record<never, never>>,
    '/dashboard/views/DashboardView': RouteRecordInfo<'/dashboard/views/DashboardView', '/dashboard/views/DashboardView', Record<never, never>, Record<never, never>>,
    '/landingpage/views/LandingPage': RouteRecordInfo<'/landingpage/views/LandingPage', '/landingpage/views/LandingPage', Record<never, never>, Record<never, never>>,
  }
}
